accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import create_user

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", create_user, name="sign_up"),
]

expenses/urls.py
from audioop import reverse
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (ExpenseCategoryCreateView, ExpenseCategoryListView, ReceiptListView, AccountCreateView, AccountListView, ExpenseCategoryListView, ReceiptCreateView)

urlpatterns = [
path("", ReceiptListView.as_view(), name="home"),
path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
path("accounts/create/", AccountCreateView.as_view(), name="account_create"),
path("accounts/""", AccountListView.as_view(), name="account_list"),
path("categories/create", ExpenseCategoryCreateView.as_view(), name="category_create"),
path("categories/""", ExpenseCategoryListView.as_view(), name="category_list"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from tkinter import CASCADE
from unicodedata import decimal
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

    # Create your models here.

receipts/forms.py
from unicodedata import category
from django.forms import ModelForm
from receipts.models import ExpenseCategory, Receipt, Account


class ReceiptForm(ModelForm):
    def __init__(self, *args, user, **kwargs):
        super(ReceiptForm, self).__init__(*args, **kwargs)
        self.fields["category"].queryset = ExpenseCategory.objects.filter(
            owner=user
        )
        self.fields["account"].queryset = Account.objects.filter(owner=user)

    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "category", "account"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login



def create_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid:
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
        context = {
            "form": form,
        }
    return render(request, "registration/signup.html", context)





# Create your views here.

receipts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Account, ExpenseCategory, Receipt
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.db.models import Count
from receipts.forms import ReceiptForm

# Account: Create View and List View


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    fields = ["name", "number"]
    template_name = "accounts/create.html"

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        # account is a variable that associates w/Account model for remembering purose. .own because Account model has a property called owner but under AccountCreateView there isn't

        account.save()
        return redirect("account_list")
        # redirect back to the account list path in urls.py


class AccountListView(ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user).annotate(
            number_receipt=Count("receipts")
        )


# Expense Category: Create View and List View
class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    fields = ["name"]
    template_name = "expense_categories/create.html"

    def form_valid(self, form):
        category = form.save(commit=False)
        category.owner = self.request.user
        category.save()
        return redirect("category_list")


class ExpenseCategoryListView(ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(
            owner=self.request.user
        ).annotate(number_receipt=Count("receipts"))

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["all"] = ExpenseCategory.objects.filter(
    #         owner=self.request.user
    #     ).annotate(number_receipt=Count("receipts"))

    #     return context


# Receipt: Create View and List View
class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    # fields = ["vendor", "total", "tax", "date", "category", "account"]
    form_class = ReceiptForm
    template_name = "receipts/create.html"

    def get_form_kwargs(self):
        kwargs = super(ReceiptCreateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form = Receipt(user=self.request.user)
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        return redirect("home")

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptListView(ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


# Create your views here.

accounts/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <nav>
      {% if user.is_authenticated %}
      <li>
        <a href="{% url 'home' %}">Receipts</a>
      </li>

      <li>
        <a href="{% url 'receipt_create' %}">Create receipts</a>
      </li>

      <li>
        <a href="{% url 'account_list' %}">Accounts</a>
      </li>

      <li>
        <a href="{% url 'account_create' %}">Create account</a>
      </li>

      <li>
        <a href="{% url 'category_list' %}">Categories</a>
      </li>

      <li>
        <a href="{% url 'category_create' %}">Create category</a>
      </li>

      <li>
        <a href="{% url 'logout' %}">Logout</a>
      </li>

      {% else %}
      <li>
        <a href="{% url 'login' %}">Login</a>
      </li>
      <li>
        <a href="{% url 'sign_up' %}">Sign Up</a>
      </li>
    </nav>
    {% endif %} {% block content %} {% endblock content %}
  </body>
</html>

receipts/templates/accounts/create.html
{% extends 'base.html' %} {% block content%}
<main>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>Create</button>
</main>

{% endblock content%}

receipts/templates/accounts/list.html
{%extends 'base.html'%} {% block content %}

<main>
  <h1>Accounts</h1>

  <table>
    <tr>
      <thead>
        <th>Name</th>
        <th>Number</th>
        <th>Number of receipts</th>
      </thead>
    </tr>
    <tbody>
      {% for account in account_list%}
      <tr>
        <td>{{account.name}}</td>
        <td>{{account.number}}</td>
        <td>{{account.number_receipt}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}

receipts/templates/expense_categories/create.html
{% extends 'base.html' %} {% block content%}

<main>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>Create</button>
</main>
{% endblock content %}

receipts/templates/expense_categories/list.html
{%extends 'base.html'%} {% block content %}

<main>
  <h1>Expense Categories</h1>
  <table>
    <tr>
      <thead>
        <th>Name</th>
        <th>Number of receipts</th>
      </thead>
    </tr>
    <tbody>
      {% for category in expensecategory_list %}

      <tr>
        <td>{{category.name}}</td>
        <td>{{category.number_receipt}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %} {% block content%}

<main>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>Create</button>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{%extends 'base.html'%} {% block content %}

<main>
  <h1>Receipts</h1>
  <table>
    <tr>
      <thead>
        <th>Vendor</th>
        <th>Total</th>
        <th>Tax</th>
        <th>Date</th>
        <th>Category</th>
        <th>Account</th>
      </thead>
    </tr>
    <tbody>
      {% for receipt in receipt_list %}
      <tr>
        <td>{{receipt.vendor}}</td>
        <td>{{receipt.total}}</td>
        <td>{{receipt.tax}}</td>
        <td>{{receipt.date}}</td>
        <td>{{receipt.category}}</td>
        {% if receipt.account != None %}
        <td>{{receipt.account}}</td>
        {% else %}
        <td>Cash</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}